# Generated by Django 4.2.25 on 2025-11-04 15:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EvaluationResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='评估时间')),
                ('seq_len', models.IntegerField(verbose_name='输入序列长度')),
                ('label_len', models.IntegerField(verbose_name='标签长度')),
                ('pred_len', models.IntegerField(verbose_name='预测长度')),
                ('d_model', models.IntegerField(verbose_name='模型维度')),
                ('n_heads', models.IntegerField(verbose_name='注意力头数')),
                ('e_layers', models.IntegerField(verbose_name='编码器层数')),
                ('d_layers', models.IntegerField(verbose_name='解码器层数')),
                ('mae', models.FloatField(verbose_name='平均绝对误差')),
                ('mse', models.FloatField(verbose_name='均方误差')),
                ('rmse', models.FloatField(verbose_name='均方根误差')),
                ('num_batches', models.IntegerField(verbose_name='评估批次数')),
                ('device', models.CharField(max_length=20, verbose_name='计算设备')),
                ('execution_time', models.FloatField(blank=True, null=True, verbose_name='执行时间(秒)')),
                ('status', models.CharField(default='success', max_length=20, verbose_name='状态')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='错误信息')),
            ],
            options={
                'verbose_name': '评估结果',
                'verbose_name_plural': '评估结果',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ModelInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='记录时间')),
                ('total_params', models.BigIntegerField(verbose_name='总参数量')),
                ('trainable_params', models.BigIntegerField(verbose_name='可训练参数量')),
                ('model_size_mb', models.FloatField(verbose_name='模型大小(MB)')),
                ('config_json', models.JSONField(verbose_name='配置信息')),
            ],
            options={
                'verbose_name': '模型信息',
                'verbose_name_plural': '模型信息',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PredictionJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='开始时间')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('status', models.CharField(choices=[('pending', '等待中'), ('running', '运行中'), ('completed', '已完成'), ('failed', '失败')], default='pending', max_length=20, verbose_name='状态')),
                ('config_path', models.CharField(max_length=500, verbose_name='配置文件路径')),
                ('checkpoint_path', models.CharField(max_length=500, verbose_name='模型检查点路径')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='错误信息')),
                ('evaluation_result', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='model_evaluator.evaluationresult', verbose_name='评估结果')),
            ],
            options={
                'verbose_name': '预测任务',
                'verbose_name_plural': '预测任务',
                'ordering': ['-created_at'],
            },
        ),
    ]
