# Generated by Django 4.2.25 on 2025-11-04 15:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('model_evaluator', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aircraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flight_id', models.CharField(max_length=20, unique=True, verbose_name='航班号')),
                ('aircraft_type', models.CharField(blank=True, max_length=50, verbose_name='机型')),
                ('callsign', models.CharField(blank=True, max_length=20, verbose_name='呼号')),
                ('registration', models.CharField(blank=True, max_length=20, verbose_name='注册号')),
                ('current_status', models.CharField(choices=[('ground', '地面'), ('takeoff', '起飞'), ('climbing', '爬升'), ('cruising', '巡航'), ('descending', '下降'), ('landing', '降落'), ('landed', '已降落')], default='ground', max_length=20, verbose_name='飞行状态')),
                ('current_latitude', models.FloatField(blank=True, null=True, verbose_name='当前纬度')),
                ('current_longitude', models.FloatField(blank=True, null=True, verbose_name='当前经度')),
                ('current_altitude', models.FloatField(blank=True, null=True, verbose_name='当前高度(m)')),
                ('current_speed', models.FloatField(blank=True, null=True, verbose_name='当前速度(m/s)')),
                ('current_heading', models.FloatField(blank=True, null=True, verbose_name='当前航向(度)')),
                ('last_update', models.DateTimeField(auto_now=True, verbose_name='最后更新时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否活跃')),
            ],
            options={
                'verbose_name': '飞机',
                'verbose_name_plural': '飞机',
            },
        ),
        migrations.CreateModel(
            name='TrackingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=100, unique=True, verbose_name='会话ID')),
                ('status', models.CharField(choices=[('active', '活跃'), ('paused', '暂停'), ('completed', '完成'), ('error', '错误')], default='active', max_length=20, verbose_name='状态')),
                ('start_time', models.DateTimeField(auto_now_add=True, verbose_name='开始时间')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='结束时间')),
                ('last_activity', models.DateTimeField(auto_now=True, verbose_name='最后活动时间')),
                ('total_data_points', models.IntegerField(default=0, verbose_name='总数据点数')),
                ('total_predictions', models.IntegerField(default=0, verbose_name='总预测次数')),
                ('average_confidence', models.FloatField(blank=True, null=True, verbose_name='平均置信度')),
                ('update_interval', models.IntegerField(default=30, verbose_name='更新间隔(秒)')),
                ('prediction_horizon', models.IntegerField(default=24, verbose_name='预测时长(步数)')),
                ('aircraft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='model_evaluator.aircraft', verbose_name='飞机')),
            ],
            options={
                'verbose_name': '跟踪会话',
                'verbose_name_plural': '跟踪会话',
                'ordering': ['-last_activity'],
            },
        ),
        migrations.CreateModel(
            name='PredictionResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prediction_time', models.DateTimeField(auto_now_add=True, verbose_name='预测时间')),
                ('base_time', models.DateTimeField(verbose_name='基准时间')),
                ('predicted_trajectory', models.JSONField(verbose_name='预测轨迹')),
                ('confidence_scores', models.JSONField(default=dict, verbose_name='置信度分数')),
                ('input_sequence_length', models.IntegerField(verbose_name='输入序列长度')),
                ('prediction_horizon', models.IntegerField(verbose_name='预测时长(步数)')),
                ('model_version', models.CharField(default='v1.0', max_length=50, verbose_name='模型版本')),
                ('mae', models.FloatField(blank=True, null=True, verbose_name='MAE')),
                ('mse', models.FloatField(blank=True, null=True, verbose_name='MSE')),
                ('rmse', models.FloatField(blank=True, null=True, verbose_name='RMSE')),
                ('processing_time_ms', models.IntegerField(blank=True, null=True, verbose_name='处理时间(毫秒)')),
                ('is_valid', models.BooleanField(default=True, verbose_name='是否有效')),
                ('aircraft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='model_evaluator.aircraft', verbose_name='飞机')),
            ],
            options={
                'verbose_name': '预测结果',
                'verbose_name_plural': '预测结果',
                'ordering': ['-prediction_time'],
                'indexes': [models.Index(fields=['aircraft', 'prediction_time'], name='model_evalu_aircraf_96845a_idx'), models.Index(fields=['prediction_time'], name='model_evalu_predict_9a6a00_idx')],
            },
        ),
        migrations.CreateModel(
            name='FlightData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(verbose_name='时间戳')),
                ('received_at', models.DateTimeField(auto_now_add=True, verbose_name='接收时间')),
                ('latitude', models.FloatField(verbose_name='纬度')),
                ('longitude', models.FloatField(verbose_name='经度')),
                ('geo_altitude', models.FloatField(verbose_name='几何高度(m)')),
                ('baro_altitude', models.FloatField(verbose_name='气压高度(m)')),
                ('speed', models.FloatField(blank=True, null=True, verbose_name='速度(m/s)')),
                ('vertical_rate', models.FloatField(blank=True, null=True, verbose_name='垂直速度(m/s)')),
                ('heading', models.FloatField(blank=True, null=True, verbose_name='航向(度)')),
                ('data_quality', models.IntegerField(default=100, verbose_name='数据质量(%)')),
                ('is_processed', models.BooleanField(default=False, verbose_name='是否已处理')),
                ('aircraft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='model_evaluator.aircraft', verbose_name='飞机')),
            ],
            options={
                'verbose_name': '飞行数据',
                'verbose_name_plural': '飞行数据',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['aircraft', 'timestamp'], name='model_evalu_aircraf_54ce20_idx'), models.Index(fields=['timestamp'], name='model_evalu_timesta_dfd10f_idx'), models.Index(fields=['is_processed'], name='model_evalu_is_proc_24dc14_idx')],
            },
        ),
    ]
